version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: zaprite-phoenixd-lightning-wallet-ui_server_1
      APP_PORT: 32400
    
  server:
    image: hezronkarani/phoenix-server-wallet:0.1.5
    user: "0:0"
    init: true
    volumes:
      - "${APP_DATA_DIR}/data/pslw:/root/.phoenix"
      - "${APP_DATA_DIR}/data/datajson:/usr/src/app/backend/dbjson"